fw.home=/Users/rajathirumal/Raja/code/java/CETL/dev/jSpine
################ DB DETAILS     ################
fw.db.url=jdbc:sqlserver://localhost:1433;databaseName=bankDB;encrypt=false;integratedSecurity=false
fw.db.user=sa
fw.db.password=BankSqlServer@123
## Available db types are
#       1. mssql
#       2.
fw.db.dbtype=MSSQL
# Default time out is 10 seconds. When provided, uses abs value.
fw.db.timeout= 2

################ logging        ################
# Absolute path to log. If not provided, the default path is <fw.home>/log
fw.log.directory=/Users/rajathirumal/Raja/code/java/CETL/dev/jSpine/log/
# OFF - turn off logging
# DEBUG
# INFO
# ERROR 
# ALL - Default
fw.log.level=ALL
# roll out - always in mb (default 100 mb)
fw.log.maxsize=100


################ PROJECT LEVEL  ################
## You can provide the project level properties here.
## You can write your own code for your project. The stpes are provided in "How to write your logic" in the README.md file.

# The below properties are mandatory.

# Absolute path of the library folder. If this is not provided, the default path is <fw.home>/custom_lib
fw.custom.libs=/Users/rajathirumal/Raja/code/java/CETL/dev/jSpine/custom_lib
# All the jar files are expected to have the below package names. This is mandatory.
fw.default.package=com.custom.cetl



################ OTHER DETAILS  ################

################ OTHER DETAILS  ################


